# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Generate new localized screenshots"
  lane :screenshots do
    capture_screenshots(scheme: "AHIS")
  end

  desc "Upload screenshots to App Store Connect"
  lane :upload_screenshots do
    api_key = app_store_connect_api_key(
      key_id: "BNQ6S2F6HQ",
      issuer_id: "69a6de71-2ecd-47e3-e053-5b8c7c11a4d1",
      key_filepath: "./fastlane/AuthKey_BNQ6S2F6HQ.p8"
    )
    upload_to_app_store(
      api_key: api_key,
      skip_binary_upload: true,
      skip_metadata: true,
      force: true,
      overwrite_screenshots: true,
      precheck_include_in_app_purchases: false,
      screenshots_path: "./screenshots"
    )
  end

  desc "Upload metadata to App Store Connect"
  lane :upload_metadata do
    api_key = app_store_connect_api_key(
      key_id: "BNQ6S2F6HQ",
      issuer_id: "69a6de71-2ecd-47e3-e053-5b8c7c11a4d1",
      key_filepath: "./fastlane/AuthKey_BNQ6S2F6HQ.p8"
    )
    upload_to_app_store(
      api_key: api_key,
      skip_binary_upload: true,
      skip_screenshots: true,
      force: true,
      precheck_include_in_app_purchases: false
    )
  end

  desc "Build and upload to TestFlight"
  lane :release do
    api_key = app_store_connect_api_key(
      key_id: "BNQ6S2F6HQ",
      issuer_id: "69a6de71-2ecd-47e3-e053-5b8c7c11a4d1",
      key_filepath: "./fastlane/AuthKey_BNQ6S2F6HQ.p8"
    )
    get_provisioning_profile(
      api_key: api_key,
      app_identifier: "glider.ninja.winch.launch",
      team_id: "XBC8ZV2BGE"
    )
    build_app(
      scheme: "AHIS",
      export_method: "app-store",
      export_options: {
        signingStyle: "manual",
        teamID: "XBC8ZV2BGE",
        provisioningProfiles: {
          "glider.ninja.winch.launch" => ENV["sigh_glider.ninja.winch.launch_appstore_profile-name"] || "match AppStore glider.ninja.winch.launch"
        }
      }
    )
    upload_to_testflight(api_key: api_key)
  end

  lane :beta do
    ensure_git_status_clean
    increment_build_number(xcodeproj: "AHIS.xcodeproj")
    commit_version_bump(xcodeproj: "AHIS.xcodeproj")
    add_git_tag
  end
end
